### ISSUE TITLE
Share button on Archive Frag will not work when there is no Archive Target

### ISSUE THREAD

**Issue by maityamit** [maityamit/Tracky-Track-your-goals-or-targets#155]
### Contact Details

maityamit308@gmail.com

### What happened?

Share button on Archive Frag will not work when there is no Archive Target. 
When Archive Goal is empty , the app crash now

### Relevant log output

```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: achivementtrackerbyamit.example.achivetracker, PID: 2455
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
        at achivementtrackerbyamit.example.achivetracker.archive_goal.ArchiveGoalFragment.screenShot(ArchiveGoalFragment.java:106)
        at achivementtrackerbyamit.example.achivetracker.archive_goal.ArchiveGoalFragment.access$000(ArchiveGoalFragment.java:42)
        at achivementtrackerbyamit.example.achivetracker.archive_goal.ArchiveGoalFragment$1.onClick(ArchiveGoalFragment.java:94)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC.
